baseURL = 'https://techtea.io/'
languageCode = 'en-us'
title = 'TechTea'
theme = 'techtea-theme'
paginatepaginate = 10
pluralizelisttitles = false

[params]
    brand = "TechTea"                      # name of your site - appears in the sidebar
    # brand_image = "/images/test.jpg"    # path to the image shown in the sidebar
    description = "Tech Made Simple" # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    favicon = "/img/people/matthew_lamont.jpg"             # path to favicon (defaults to favicon.png)
    author = "Matthew"
    author_url = "https://techtea.io"


    # Links to your socials.  Comment or delete any you don't need/use. 
    github_url = "https://github.com/matthew30903"
    youtube_url = "https://www.youtube.com/@TechTeaWithMatthew"
    email_url = "mailto:hello@mattlamont.com"

    # NOTE: If you don't want to use RSS, comment or delete the following lines
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "articles"


    # Hex colors for your content in light mode.
    text_color = "#222"             # default is #222
    content_bg_color = "#d9d0b4"    # default is #FAF9F6
    link_color = "#53917E"          # default is #268bd2
    tag_link_color = "#eee"
    tag_bkg_color = "#53917E"


    text_color_dark = "#eee"                # default is #eee
    content_bg_color_dark = "#152028"       # default is #121212
    link_color_dark = "#268bd2"             # default is #268bd2
    code_color = "#bf616a"                  # default is #bf616a
    code_background_color = "#272822"       # default is #E5E5E5
    code_color_dark = "#ff7f7f"             # default is #ff7f7f
    code_background_color_dark = "#393D47"  # default is #393D47
    tag_link_color_dark = "#eee"
    tag_bkg_color_dark = "#268bd2"

    light_dark_button_color = "#FFF"
    light_dark_button_bkg_color = "#515151"

[menus]
  [[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
  [[menus.main]]
  name = 'Articles'
  pageRef = '/articles'
  weight = 20
  [[menus.main]]
  name = 'Notes'
  pageRef = '/notes'
  weight = 30
    [[menus.main]]
  name = 'Reviews'
  pageRef = '/reviews'
  weight = 40
  [[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 50
  [[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 60

[permalinks]
    [permalinks.page]
        articles = '/articles/:year/:slugorcontentbasename/'
    [permalinks.section]
        articles = '/articles/'

[taxonomies]
    series = 'series'
    tags = 'tags'
    category = "categories"
    author = "authors"
    brand = "brands"
    tea = "teas"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[mediaTypes]
    [mediaTypes."application/feed+json"]
    suffixes = ["json"]

[outputFormats.jsonfeed]
  mediaType = "application/feed+json"
  baseName = "feed"
  rel = "alternate"
  isPlainText = true

[outputs]
  home = ["HTML", "RSS", "jsonfeed"]
  section = ["HTML", "RSS", "jsonfeed"]
  page = ["HTML"]